### PR TITLE
Changed a few words for the description of the dataset in README.md file

### PR DESCRIPTION
**Pull request by jiangshaohua1997**
I have made a minor cleaning up version for the dataset section in the README.md file. Did not add new information.

I noticed that the comparison between my branch and the main branch is a bit funny. I actually only changed three words on lines 19 and 20. You can ignore the one for "README-checkpoint.md" since it might be automatically generated.

### CODE REVIEW

**Comment by KafkaNoNeko** [comment]
Hi, it seems that your repl.it is suing the older version of the README.  I ma not sure why this is happening (happened to me too), but I just created a new repl session

Create --> import from GitHub -- >choose the group project

Not sure if this is efficient, but its the fastest solution I've found

**Comment by jiangshaohua1997** [comment]
> Hi, it seems that your repl.it is using the older version of the README. I am not sure why this is happening (happened to me too), but I just created a new repl session
> 
> Create --> import from GitHub -- >choose the group project
> 
> Not sure if this is efficient, but its the fastest solution I've found

I was using the original way for Github recently by cloning it to my local computer, editing, and pushing it back to Github. I have not used repl.it very often since I did not find a way to use Jupiter Lab efficiently on it, but I would love to have a try. Could you tell me how I can join the new session?

**Comment by KafkaNoNeko** [comment]
Oh I see!  I think repl.it is better used to edit READMEs and not for ipynb files.  I agree that it is easier to just make the changes in one go locally.  I just tried using repl.it because the milestone said that we should try it out haha

Did you do 'git pull' before working on the README?  That might have cause the two file versions to be different

**Comment by jiangshaohua1997** [comment]
> Oh I see! I think repl.it is better used to edit READMEs and not for ipynb files. I agree that it is easier to just make the changes in one go locally. I just tried using repl.it because the milestone said that we should try it out haha
> 
> Did you do 'git pull' before working on the README? Not doing that might have caused the two file versions to be different

I did, but sometimes it did not download the correct version, especially when I was using a branch that I created locally. However, when I work on the main branch, everything went well.

**Comment by jiangshaohua1997** [comment]
> > Oh I see! I think repl.it is better used to edit READMEs and not for ipynb files. I agree that it is easier to just make the changes in one go locally. I just tried using repl.it because the milestone said that we should try it out haha
> > Did you do 'git pull' before working on the README? Not doing that might have caused the two file versions to be different
> 
> I did, but sometimes it did not download the correct version, especially when I was using a branch that I created locally. However, when I work on the main branch, everything went well.

I think that my computer automatically generated some files called "DS.Store" and "checkpoints" that really prevents me from pulling and switching branches

**Comment by KafkaNoNeko** [comment]
I see.  That is weird.  I have check points as well, and I could create branches using that

**Pull request closed without merging**
